### ISSUE TITLE
Cannot run OSX version

### ISSUE THREAD

**Issue by blakehan** [choss/java-xci-splitter#1]
***WARNING: Display must be created on main thread due to Cocoa restrictions.
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4533)
	at org.eclipse.swt.SWT.error(SWT.java:4448)
	at org.eclipse.swt.SWT.error(SWT.java:4419)
	at org.eclipse.swt.widgets.Display.error(Display.java:1090)
	at org.eclipse.swt.widgets.Display.createDisplay(Display.java:840)
	at org.eclipse.swt.widgets.Display.create(Display.java:823)
	at org.eclipse.swt.graphics.Device.<init>(Device.java:129)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:722)
	at org.eclipse.swt.widgets.Display.<init>(Display.java:713)
	at org.eclipse.swt.widgets.Display.getDefault(Display.java:1420)
	at org.insanedevelopment.nx.xci.cutter.frontend.swt.XciSplitterSwtGui.open(XciSplitterSwtGui.java:56)
	at org.insanedevelopment.nx.xci.cutter.frontend.swt.XciSplitterSwtGui.main(XciSplitterSwtGui.java:46)

**Comment by choss** [comment]
Did you start it from the command line with -XstartOnFirstThread?

**Comment by choss** [comment]
I have some ideas how to improve the user experience for the osx version. Will work on them in a couple of days.

**Comment by choss** [comment]
Hopefully fixed in version 1.2.1
